### ISSUE TITLE
Custom Logo

### ISSUE THREAD

**Issue by elalemanyo** [creativecoder/piwik-heroku#3]
Hi, Is there a way to add custom logo?

Thanks!

**Comment by creativecoder** [comment]
Do you mean using the custom logo feature in Settings > System > General Settings?

Looks like when you add a logo, it is saved as `/misc/user/logo-header.png`.

The `/misc` folder is copied into `vendor/piwik/piwik` as part of the composer install process, because some plugin files installed by composer need to be copied there. So if you add your logo image to the repo using the same filename and path (relative to the root of the repo), it should get copied when you rebuild the app (but I haven't tested this myself).

**Comment by elalemanyo** [comment]
ok, I would try. But can you tell me how should be the path?
`cp -R images/* vendor/piwik/piwik/misc/user/`? And in the repo I put inside `images` directory all the images?

**Comment by elalemanyo** [comment]
But `misc` is in the gitingore

**Comment by creativecoder** [comment]
You are very right! As a workaround, try modifying `.gitignore` by remove `misc/` and replacing with the following:

```
misc/*
!misc/user/
!misc/user/*
```

That should let you add the image to the repo in that `misc/user`

---

Alternatively, a "better" way to do this would be to mount external storage to the app container so that files stored in `misc/user` aren't wiped out when the application is rebuilt.

**Comment by creativecoder** [comment]
Also, your example of adding `cp -R images/* vendor/piwik/piwik/misc/user/` to the post-install-cmd script should work, as well.

**Comment by elalemanyo** [comment]
Works great!! Thanks!
