### ISSUE TITLE
Upgrade Matomo 3.8.1 ? 

### ISSUE THREAD

**Issue by Lucas-Geitner** [creativecoder/piwik-heroku#6]
Hello,

Thanks for the work here !

I would like to upgrade to 3.8.1 but the compose configuration file is tricky for me and they are some invalid dependancy,

do you think it's possible to update it ?

Thanks a lots !

**Comment by creativecoder** [comment]
Re-requiring the package usually updates to the latest version... `composer require piwik/piwik`.

I did this just now and updated `master`... only goes up to 3.8.0.

When I run `composer require piwik/piwik:3.8.1`, I get

```
  Problem 1
    - Installation request for piwik/piwik 3.8.1 -> satisfiable by piwik/piwik[3.8.1].
    - piwik/piwik 3.8.1 requires jshrink =1.3.1 -> no matching package found.
```

Looks like the 3.8.1 release requires a composer package that doesn't exist: https://github.com/matomo-org/matomo/blob/02247d038c935c802db4ae76f4b4be3b41c4c240/composer.json#L31

There's not really anything I can do about this since the problem is upstream. I suggest opening an issue at https://github.com/matomo-org/matomo/issues.

**Comment by creativecoder** [comment]
Note that I was able to resolve this through the workaround described here: https://github.com/matomo-org/matomo/issues/14874.

This repo now has the most recent version of Matomo
